before_install:
  - sudo apt-get update
  - sudo apt-get install --yes build-essential
  - sudo apt-get install --yes git
  - sudo apt-get install gfortran

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -q -f environment.yml
  - pip install simpy
  - source activate tyssue-taylor
  - pwd
  - cd ..
  - git clone https://github.com/madebr/pyOpt.git
  - cd pyOpt
  - python setup.py install
  - cd ../tyssue-taylor
  - conda install pytest pytest-cov
  - pip install coveralls

install:
  - python setup.py install

script:
  - pytest tests

after_success:
  - coveralls
